- name: Install default packages
  yum:
    name:  '{{ item }}'
    state: latest
  with_items:
    # System tools
    - sudo
    # Compression
    - zip
    - unzip
    - bzip2
    # Graphic tools
    - ImageMagick
    # Networking tools
    - wget
    - curl
    - net-tools
    # Utils
    - moreutils
    - bind-utils