---

- name: Install ssmtp
  apt:
    name:  '{{ item }}'
    state: present
  when: ansible_distribution == 'Ubuntu'
  with_items:
    - ssmtp

- name: Install ssmtp
  yum:
    name:  '{{ item }}'
    state: present
  when: ansible_distribution == 'CentOS'
  with_items:
    - ssmtp
