#######################################
# Main php container
#
# for this container you have to remove
# following entries from .dockerignore:
#
# etc/*
# provision/*
# app/*
#
#######################################
main:
  build: .
  dockerfile: Dockerfile.cloud
  links:
    - mysql
    #- postgres
    #- mail
    #- solr
    #- elasticsearch
    #- redis
    #- memcached
    #- ftp
  ports:
    - "8000:80"
    - "8443:443"
    - "10022:22"
  volumes_from:
    - storage
  env_file:
    - etc/environment.yml
    - etc/environment.production.yml

#######################################
# MySQL server
#######################################
mysql:
  build: docker/mysql
  #dockerfile: MySQL-5.5
  dockerfile: MySQL-5.6
  #dockerfile: MySQL-5.7
  #dockerfile: MariaDB-5.5
  #dockerfile: MariaDB-10
  #dockerfile: Percona-5.5
  #dockerfile: Percona-5.6
  volumes_from:
    - storage
  env_file:
    - etc/environment.yml
    - etc/environment.production.yml

#######################################
# PostgreSQL server
#######################################
#postgres:
#  build: docker/postgres/
#  volumes_from:
#    - storage
#  env_file:
#    - etc/environment.yml
#    - etc/environment.production.yml

#######################################
# Solr server
#######################################
#solr:
#  build: docker/solr/
#  volumes_from:
#    - storage
#  environment:
#    - SOLR_STORAGE=/storage/solr/server-master/
#  env_file:
#    - etc/environment.yml
#    - etc/environment.production.yml

#######################################
# Elasticsearch
#######################################
#elasticsearch:
#  build: docker/elasticsearch/
#  volumes_from:
#    - storage
#  env_file:
#    - etc/environment.yml
#    - etc/environment.production.yml

#######################################
# Redis
#######################################
#redis:
#  build: docker/redis/
#  volumes_from:
#    - storage
#  env_file:
#    - etc/environment.yml
#    - etc/environment.production.yml

#######################################
# Memcached
#######################################
#memcached:
#  build: docker/memcached/
#  volumes_from:
#    - storage
#  env_file:
#    - etc/environment.yml
#    - etc/environment.production.yml

#######################################
# Mailcatcher
#######################################
#mail:
#  build: docker/mail/
#  env_file:
#    - etc/environment.yml
#    - etc/environment.production.yml

#######################################
# FTP (vsftpd)
#######################################
#ftp:
#  build: docker/vsftpd/
#  volumes_from:
#    - sourcecode
#    - storage
#  env_file:
#    - etc/environment.yml
#    - etc/environment.production.yml

#######################################
# Storage
#######################################
storage:
  build: docker/storage/
  volumes:
    - /data
