version: '2'
services:
  #######################################
  # PHP application Docker container
  #######################################
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    links:
      - mysql
      #- postgres
      #- mail
      #- solr
      #- elasticsearch
      #- redis
      #- memcached
      #- ftp
    ports:
      - "8000:80"
      - "8443:443"
      - "10022:22"
    volumes:
      - ./app/:/app/
    volumes_from:
      - storage
    env_file:
      - etc/environment.yml
      - etc/environment.production.yml

  #######################################
  # MySQL server
  #######################################
  mysql:
    build:
      context: docker/mysql/
      #dockerfile: MySQL-5.5.Dockerfile
      dockerfile: MySQL-5.6.Dockerfile
      #dockerfile: MySQL-5.7.Dockerfile
      #dockerfile: MariaDB-5.5.Dockerfile
      #dockerfile: MariaDB-10.Dockerfile
      #dockerfile: Percona-5.5.Dockerfile
      #dockerfile: Percona-5.6.Dockerfile
      #dockerfile: Percona-5.7.Dockerfile
    volumes_from:
      - storage
    env_file:
      - etc/environment.yml
      - etc/environment.production.yml

  #######################################
  # PostgreSQL server
  #######################################
  #postgres:
  #  build:
  #    context: docker/postgres/
  #    dockerfile: Postgres-9.4.Dockerfile
  #    dockerfile: Postgres-9.5.Dockerfile
  #  ports:
  #    - 15432:5432
  #  volumes_from:
  #    - storage
  #  env_file:
  #    - etc/environment.yml
  #    - etc/environment.production.yml

  #######################################
  # Solr server
  #######################################
  #solr:
  #  build:
  #    context: docker/solr/
  #  ports:
  #    - 18983:8983
  #  volumes_from:
  #    - storage
  #  environment:
  #    - SOLR_STORAGE=/storage/solr/server-master/
  #  env_file:
  #    - etc/environment.yml
  #    - etc/environment.production.yml

  #######################################
  # Elasticsearch
  #######################################
  #elasticsearch:
  #  build:
  #    context: docker/elasticsearch/
  #  ports:
  #    - 19200:9200
  #    - 19300:9300
  #  volumes_from:
  #    - storage
  #  env_file:
  #    - etc/environment.yml
  #    - etc/environment.production.yml

  #######################################
  # Redis
  #######################################
  #redis:
  #  build:
  #    context: docker/redis/
  #  volumes_from:
  #    - storage
  #  env_file:
  #    - etc/environment.yml
  #    - etc/environment.production.yml

  #######################################
  # Memcached
  #######################################
  #memcached:
  #  build:
  #    context: docker/memcached/
  #  volumes_from:
  #    - storage
  #  env_file:
  #    - etc/environment.yml
  #    - etc/environment.production.yml

  #######################################
  # FTP (vsftpd)
  #######################################
  #ftp:
  #  build:
  #    context: docker/vsftp/
  #  volumes_from:
  #    - storage
  #  volumes:
  #    - ./:/application/
  #  env_file:
  #    - etc/environment.yml
  #    - etc/environment.production.yml

  #######################################
  # Storage
  #######################################
  storage:
    build:
      context: docker/storage/
    volumes:
      - /storage
