typo3:
  build: docker/typo3/
  links:
    - solr
    - mysql
  volumes:
    - ./:/var/www/
  volumes_from:
    - storage
  env_file:
    - docker-env.yml

nginx:
  build: docker/nginx/
  ports:
    - 8000:80
  links:
    - fpm
  volumes_from:
    - typo3
  env_file:
    - docker-env.yml

#httpd:
#  build: docker/httpd/
#  ports:
#    - 8000:80
#  links:
#    - fpm
#  volumes_from:
#    - typo3
#  env_file:
#    - docker-env.yml

fpm:
  build: docker/php-fpm/
  links:
    - solr
    - mysql
  volumes_from:
    - typo3
  env_file:
    - docker-env.yml

mysql:
  build: docker/mysql/
  ports:
    - 13306:3306
  env_file:
    - docker-env.yml

solr:
  build: docker/solr/
  ports:
    - 18983:8983
  volumes_from:
    - storage
  environment:
    - SOLR_STORAGE=/data/solr/server-master/
  env_file:
    - docker-env.yml

#elasticsearch:
#  build: docker/elasticsearch/
#  ports:
#    - 19200:9200
#    - 19300:9300
#  env_file:
#    - docker-env.yml

storage:
  build: docker/storage/
  volumes:
    - /data
  command: true