typo3:
  build: docker/typo3/
  links:
    - mysql
  volumes:
    - ./htdocs:/var/www
  env_file:
    - docker-env.yml

nginx:
  build: docker/nginx/
  ports:
    - 8000:80
  links:
    - fpm
  volumes_from:
    - typo3
  env_file:
    - docker-env.yml

fpm:
  build: docker/php-fpm/
  links:
    - mysql
  volumes_from:
    - typo3
  env_file:
    - docker-env.yml

mysql:
  image: mysql:5.5
  ports:
    - 3306:3306
  env_file:
    - docker-env.yml