typo3:
  build: docker/typo3/
  links:
    - solr
    - mysql
  volumes:
    - ./htdocs:/var/www/html
  env_file:
    - docker-env.yml

nginx:
  build: docker/nginx/
  ports:
    - 8000:80
  links:
    - fpm
  volumes_from:
    - typo3
  env_file:
    - docker-env.yml

fpm:
  build: docker/php-fpm/
  links:
    - solr
    - mysql
  volumes_from:
    - typo3
  env_file:
    - docker-env.yml

mysql:
  build: docker/mysql/
  ports:
    - 3306:3306
  env_file:
    - docker-env.yml

solr:
  build: docker/solr/
  ports:
    - 8983:8983
  env_file:
    - docker-env.yml
