#######################################
# Main php container
#######################################
main:
  build: docker/main/
  links:
    - mysql
    #- mail
    #- solr
    #- elasticsearch
    #- redis
    #- memcached
  volumes:
    - ./:/docker/
    - /tmp/debug/:/tmp/debug/
  volumes_from:
    - storage
  # cap and privileged needed for slowlog
  cap_add:
    - SYS_PTRACE
  privileged: true
  env_file:
    - docker-env.yml

#######################################
# Webserver
#######################################
web:
  #build: docker/httpd/
  build: docker/nginx/
  ports:
    - 8000:80
    - 8443:443
  links:
    - main
  volumes_from:
    - main
    - storage
  env_file:
    - docker-env.yml

#######################################
# MySQL server
#######################################
mysql:
  build: docker/mysql/
  ports:
    - 13306:3306
  volumes_from:
    - storage
  volumes:
    - /tmp/debug/:/tmp/debug/
  env_file:
    - docker-env.yml

#######################################
# Solr server
#######################################
#solr:
#  build: docker/solr/
#  ports:
#    - 18983:8983
#  volumes_from:
#    - storage
#  environment:
#    - SOLR_STORAGE=/data/solr/server-master/
#  env_file:
#    - docker-env.yml

#######################################
# Elasticsearch
#######################################
#elasticsearch:
#  build: docker/elasticsearch/
#  ports:
#    - 19200:9200
#    - 19300:9300
#  volumes_from:
#    - storage
#  env_file:
#    - docker-env.yml

#######################################
# Redis
#######################################
#redis:
#  build: docker/redis/
#  volumes_from:
#    - storage
#  env_file:
#    - docker-env.yml

#######################################
# Memcached
#######################################
#memcached:
#  build: docker/memcached/
#  volumes_from:
#    - storage
#  env_file:
#    - docker-env.yml

#######################################
# Mailcatcher
#######################################
#mail:
#  build: docker/mail/
#  ports:
#    - 1080:1080
#  env_file:
#    - docker-env.yml

#######################################
# Storage
#######################################
storage:
  build: docker/storage/
  volumes:
    - /data
