main:
  build: docker/main/
  links:

    - mysql
    #- solr
    #- elasticsearch
    #- redis
    #- memcached
  volumes:
    - ./:/docker/
    - /tmp/debug/:/tmp/debug/
  volumes_from:
    - storage
  env_file:
    - docker-env.yml

web:
  build: docker/httpd/
  #build: docker/nginx/
  ports:
    - 8000:80
  links:
    - main
  volumes_from:
    - main
    - storage
  env_file:
    - docker-env.yml

mysql:
  build: docker/mysql/
  ports:
    - 13306:3306
  volumes_from:
    - storage
  volumes:
    - /tmp/debug/:/tmp/debug/
  env_file:
    - docker-env.yml

#solr:
#  build: docker/solr/
#  ports:
#    - 18983:8983
#  volumes_from:
#    - storage
#  environment:
#    - SOLR_STORAGE=/data/solr/server-master/
#  env_file:
#    - docker-env.yml

#elasticsearch:
#  build: docker/elasticsearch/
#  ports:
#    - 19200:9200
#    - 19300:9300
#  volumes_from:
#    - storage
#  env_file:
#    - docker-env.yml

#redis:
#  build: docker/redis/
#  volumes_from:
#    - storage
#  env_file:
#    - docker-env.yml

#memcached:
#  build: docker/memcached/
#  volumes_from:
#    - storage
#  env_file:
#    - docker-env.yml

storage:
  build: docker/storage/
  volumes:
    - /data
