---

- name: Install mysql client
  apt:
    name:  '{{ item }}'
    state: present
  when: ansible_distribution == 'Ubuntu'
  with_items:
    - mysql-client

- name: Install mysql client
  yum:
    name:  '{{ item }}'
    state: present
  when: ansible_distribution == 'CentOS'
  with_items:
    - mysql
