- name: Install default packages
  apt:
    pkg:   '{{ item }}'
    state: latest
  with_items:
    # System tools
    - sudo
    # Compression
    - zip
    - unzip
    - bzip2
    # Graphic tools
    - graphicsmagick
    # Networking tools
    - wget
    - curl
    # Utils
    - moreutils
    - dnsutils