# create a directory if it doesn't exist
- name: Create /home/.ssh/
  file:
    path:  /home/.ssh/
    state: directory
    mode:  0750
    owner: "{{ DOCKER.CLI_USER }}"
    group: "{{ DOCKER.CLI_USER }}"

- name: Sync etc/ssh/ to /home/.ssh
  local_action: synchronize src=/opt/docker/etc/ssh/ dest=/home/.ssh/ perms=no
  ignore_errors: True

- name: Fix /home/.ssh/ permissions
  file:
    path:  /home/.ssh/
    state: directory
    owner: "{{ DOCKER.CLI_USER }}"
    group: "{{ DOCKER.CLI_USER }}"
    recurse: yes
  ignore_errors: True

- name: Fix ssh key permissions (if exists)
  file:
    path:  /home/.ssh/id_rsa
    mode:  0600
    owner: "{{ DOCKER.CLI_USER }}"
    group: "{{ DOCKER.CLI_USER }}"
  ignore_errors: True
