---

#############################
# Ubuntu
#############################

- include: ubuntu/install.yml
  when: ansible_distribution == 'Ubuntu'
  tags:
    - bootstrap

- include: ubuntu/blackfire.yml
  when: ansible_distribution == 'Ubuntu'
  tags:
    - bootstrap

- include: ubuntu/configuration.yml
  when: ansible_distribution == 'Ubuntu'
  tags:
    - entrypoint

- include: ubuntu/modules.yml
  when: ansible_distribution == 'Ubuntu'
  tags:
    - entrypoint

#############################
# CentOS
#############################

- include: centos/install.yml
  when: ansible_distribution == 'CentOS'
  tags:
    - bootstrap

- include: centos/blackfire.yml
  when: ansible_distribution == 'CentOS'
  tags:
    - bootstrap

- include: centos/configuration.yml
  when: ansible_distribution == 'CentOS'
  tags:
    - entrypoint

- include: centos/modules.yml
  when: ansible_distribution == 'CentOS'
  tags:
    - entrypoint
