- name: Configure php-fpm (pool www.conf)
  lineinfile:
    dest:   /etc/php-fpm.d/www.conf
    regexp: '^{{ item.key }}[\s]*='
    line:   '{{ item.key }} = {{ item.value }}'
  with_items:
   # User
   - { key: 'user',  value: '{{ DOCKER.CLI_USER }}' }
   - { key: 'group', value: '{{ DOCKER.CLI_USER }}' }
   # Env
   - { key: 'env[SYMFONY_ENV]',   value: '{{ DOCKER.SYMFONY_ENV }}' }
   - { key: 'env[SYMFONY_DEBUG]', value: '{{ DOCKER.SYMFONY_DEBUG }}' }

- name: Set development environment php.ini
  file:
    src:  '/opt/docker/etc/php/development.ini'
    dest: '/opt/docker/etc/php/php.ini'
    state: link
  when: PROVISION.CONTEXT == "development" or PROVISION.CONTEXT == ""

- name: Enable production environment php.ini
  file:
    src:  '/opt/docker/etc/php/production.ini'
    dest: '/opt/docker/etc/php/php.ini'
    state: link
  when: PROVISION.CONTEXT == "production"

- name: Truncate log files
  command: 'cp /dev/null {{ item }}'
  with_items:
   - '/tmp/php.slow.log'
   - '/tmp/php.error.log'
   - '/tmp/php.access.log'
