---

PROVISION:
  CONTEXT: "{{ lookup('env','PROVISION_CONTEXT') }}"

  PHP:
    DISTRIBUTION: "{{ lookup('env','PROVISION_PHP_DISTRIBUTION') }}"

    BLACKFIRE: "{{ lookup('env','PROVISION_PHP_BLACKFIRE') }}"
    XDEBUG:    "{{ lookup('env','PROVISION_PHP_XDEBUG') }}"

DOCKER:
  # System
  EFFECTIVE_UID: "{{ lookup('env','EFFECTIVE_UID') }}"
  EFFECTIVE_GID: "{{ lookup('env','EFFECTIVE_GID') }}"
  CLI_USER:      "{{ lookup('env','CLI_USER') }}"
  CLI_SCRIPT:    "{{ lookup('env','CLI_SCRIPT') }}"

  # http
  DOCUMENT_ROOT:  "{{ lookup('env','DOCUMENT_ROOT') }}"
  DOCUMENT_INDEX: "{{ lookup('env','DOCUMENT_INDEX') }}"


  # MySQL
  MYSQL_ROOT_PASSWORD: "{{ lookup('env','MYSQL_ROOT_PASSWORD') }}"
  MYSQL_USER:          "{{ lookup('env','MYSQL_USER') }}"
  MYSQL_PASSWORD:      "{{ lookup('env','MYSQL_PASSWORD') }}"
  MYSQL_DATABASE:      "{{ lookup('env','MYSQL_DATABASE') }}"

  # PostgreSQL
  POSTGRES_USER:     "{{ lookup('env','POSTGRES_USER') }}"
  POSTGRES_PASSWORD: "{{ lookup('env','POSTGRES_PASSWORD') }}"

  # FTP
  FTP_USER:     "{{ lookup('env','FTP_USER') }}"
  FTP_PASSWORD: "{{ lookup('env','FTP_PASSWORD') }}"
  FTP_PATH:     "{{ lookup('env','FTP_PATH') }}"

  # Mail
  MAIL_GATEWAY: "{{ lookup('env','MAIL_GATEWAY') }}"

  # DNS
  DNS_DOMAIN: "{{ lookup('env','DNS_DOMAIN') }}"

  # Context
  SYMFONY_ENV:     "{{ lookup('env','SYMFONY_ENV') }}"
  SYMFONY_DEBUG:   "{{ lookup('env','SYMFONY_DEBUG') }}"
  CAKE_ENV:        "{{ lookup('env','CAKE_ENV') }}"
  YII_ENVIRONMENT: "{{ lookup('env','YII_ENVIRONMENT') }}"
