- name: Configure php-fpm (pool www.conf)
  lineinfile:
    dest:   /etc/php5/fpm/pool.d/www.conf
    regexp: '^{{ item.key }}[\s]*='
    line:   '{{ item.key }} = {{ item.value }}'
  with_items:
   # Env
   - { key: 'env[TYPO3_CONTEXT]',    value: '{{ DOCKER.TYPO3_CONTEXT }}' }
   - { key: 'env[FLOW_CONTEXT]',     value: '{{ DOCKER.FLOW_CONTEXT }}' }
   - { key: 'env[FLOW_REWRITEURLS]', value: '{{ DOCKER.FLOW_REWRITEURLS }}' }

- name: Set development environment php.ini
  file:
    src:  '/docker/etc/php/development.ini'
    dest: '/opt/docker/conf/php.ini'
    force: yes
    state: link
  when: PROVISION.CONTEXT == "development" or PROVISION.CONTEXT == ""

- name: Enable production environment php.ini
  file:
    src:  '/docker/etc/php/production.ini'
    dest: '/opt/docker/conf/php.ini'
    force: yes
    state: link
  when: PROVISION.CONTEXT == "production"

- name: Truncate log files
  command: 'cp /dev/null {{ item }}'
  with_items:
   - '/tmp/php.slow.log'
   - '/tmp/php.error.log'
   - '/tmp/php.access.log'
