- name: Install dnsmasqd
  apt:
    name:  '{{ item }}'
    state: latest
  with_items:
    - dnsmasq

- name: Configure dnsmasq
  lineinfile:
    dest:   /etc/dnsmasq.conf
    regexp: '^[\s]*{{ item.key }}[\s]*='
    line:   '{{ item.key }}={{ item.value }}'
  with_items:
   - { key: 'user',     value: 'root' }
   - { key: 'conf-dir', value: '/etc/dnsmasq.d' }

