- name: Install default packages
  apt:
    name:  '{{ item }}'
    state: present
  with_items:
    # System tools
    - sudo
    # Compression
    - zip
    - unzip
    - bzip2
    # Graphic tools
    - graphicsmagick
    # Networking tools
    - wget
    - curl
    - net-tools
    # Utils
    - moreutils
    - dnsutils