- name: Install packages (system tools)
  apt:
    name:  '{{ item }}'
    state: present
  with_items:
    - sudo

- name: Install packages (compression tools)
  apt:
    name:  '{{ item }}'
    state: present
  with_items:
    - zip
    - unzip
    - bzip2

- name: Install packages (graphic tools)
  apt:
    name:  '{{ item }}'
    state: present
  with_items:
    - imagemagick
    - graphicsmagick

- name: Install packages (network tools)
  apt:
    name:  '{{ item }}'
    state: present
  with_items:
    - wget
    - curl
    - net-tools
    - rsync

- name: Install packages (general tools)
  apt:
    name:  '{{ item }}'
    state: present
  with_items:
    - moreutils
    - dnsutils
