---

- name: Cleanup apt
  command: apt-get clean -y
  when: ansible_distribution == 'Ubuntu'

- name: Cleanup apt
  command: apt-get autoclean -y
  when: ansible_distribution == 'Ubuntu'

- name: Cleanup yum
  command: yum clean all
  when: ansible_distribution == 'CentOS'
